import Card from '@/components/Dashboard'
import Layout from '@/components/Layout'
import Head from 'next/head'
import AddCategory from './Categories'
import ForgotPassword from './ResetPassword'
import Login from './Login'
import ManageProfile from './ManageProfile'
import Signup from './SignUp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
{/*    
    <Card/> */}
    <AddCategory/>
     
          
      
      </main>
    </>
  )
}
